# Generated by Django 5.0.3 on 2024-04-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='UnitSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitSite_Venue', models.CharField(blank=True, max_length=500, null=True)),
                ('local_name', models.CharField(max_length=100)),
                ('TarrifPerPeron_Low_Season', models.FloatField(default=0.0)),
                ('TarrifPerPeron_Mid_Season', models.FloatField(default=0.0)),
                ('TarrifPerPeron_High_Season', models.FloatField(default=0.0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_content.venue')),
            ],
        ),
    ]
