# Generated by Django 5.0.3 on 2024-04-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0003_alter_venue_name_unitsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistrationNo', models.CharField(blank=True, max_length=50, null=True)),
                ('YearModel', models.CharField(blank=True, max_length=100, null=True)),
                ('Max_Pax', models.IntegerField()),
                ('AvailableVenue', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unit_images/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_content.unit')),
            ],
        ),
    ]
