# Generated by Django 5.0.3 on 2024-04-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0004_event_unit_unitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='venue',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_content.venue'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='AvailableVenue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
