# Generated by Django 5.0.3 on 2024-04-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0005_unit_venue_alter_unit_availablevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitAffected', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField()),
                ('unitUnavailabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_content.unit')),
            ],
        ),
    ]
