# Generated by Django 5.0.3 on 2024-04-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0006_booking_unavailabledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailabledate',
            name='date',
        ),
        migrations.AddField(
            model_name='unavailabledate',
            name='fromDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unavailabledate',
            name='toDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
