# Generated by Django 5.0.3 on 2024-04-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0008_booking_bookingunit_booking_bookinguser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unavailabledate',
            old_name='fromDate',
            new_name='end_Date',
        ),
        migrations.RenameField(
            model_name='unavailabledate',
            old_name='toDate',
            new_name='start_date',
        ),
    ]
