# Generated by Django 5.0.3 on 2024-04-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0009_rename_fromdate_unavailabledate_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='venue',
        ),
    ]
