# Generated by Django 5.0.3 on 2024-04-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0010_remove_booking_unit_remove_booking_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='end_Date',
        ),
    ]
