# Generated by Django 5.0.3 on 2024-04-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0011_rename_end_date_booking_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
