# Generated by Django 5.0.3 on 2024-04-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0012_remove_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailabledate',
            name='unitUnavailabe',
        ),
    ]
