# Generated by Django 5.0.3 on 2024-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0013_remove_unavailabledate_unitunavailabe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unavailabledate',
            old_name='end_Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='BookingUnit',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='BookingUser',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='BookingVenue',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_Date',
        ),
        migrations.RemoveField(
            model_name='unavailabledate',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='unavailabledate',
            name='unitAffected',
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
