# Generated by Django 5.0.3 on 2024-04-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0014_rename_end_date_unavailabledate_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unavailabledate',
            old_name='date',
            new_name='end_Date',
        ),
        migrations.AddField(
            model_name='unavailabledate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unavailabledate',
            name='unitAffected',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
